<?php

namespace AppBundle\Repository;

/**
 * IssledovanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssledovanieRepository extends \Doctrine\ORM\EntityRepository
{
    //все исследования в выбранный период
    public function issledovaniyaAll($id, $dateOt, $dateDo)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT i.id, i.nomer, i.date, i.all_count, i.ne_sootv FROM AppBundle:Issledovanie i
                WHERE i.organization = :id and i.date >= :dateOt and i.date <= :dateDo 
                GROUP BY i.id
            ')
            ->setParameter('id', $id)
            ->setParameter('dateOt', $dateOt)
            ->setParameter('dateDo', $dateDo)
            ->getResult();
    }

    public function isslShowPokazatels($issl_id)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT pi.id, pi.description, pi.pokazatel FROM AppBundle:PokazatelsIssledovaniya pi
                JOIN pi.issledovanie i
                WHERE i.id = :issl_id        
            ')
            ->setParameter('issl_id', $issl_id)
            ->getResult();
    }

    //общее число в отчетах по типу
    public function commonAll($dateOt, $dateDo)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT org.name_full, sum(i.all_count), sum(i.ne_sootv), it.name FROM AppBundle:Issledovanie i
                JOIN i.issledovanieType it
                JOIN i.organization org
                WHERE i.date >= :dateOt and i.date <= :dateDo 
                GROUP BY i.organization, i.issledovanieType
            ')
            ->setParameter('dateOt', $dateOt)
            ->setParameter('dateDo', $dateDo)
            ->getResult();
    }
}
