<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IssledovanieFkuzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssledovanieFkuzRepository extends EntityRepository
{
    //общее число в отчетах по типу
    public function commonAll($dateOt, $dateDo)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT f.name_full, sum(if.all_count), sum(if.ne_sootv), it.name FROM AppBundle:IssledovanieFkuz if
                JOIN if.issledovanieType it
                JOIN if.fkuz f
                WHERE if.date >= :dateOt and if.date <= :dateDo 
                GROUP BY if.fkuz, if.issledovanieType
            ')
            ->setParameter('dateOt', $dateOt)
            ->setParameter('dateDo', $dateDo)
            ->getResult();
    }

    //все исследования в выбранный период
    public function issledovaniyaAll($id, $dateOt, $dateDo)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT if.id, if.nomer, if.date, if.all_count, if.ne_sootv FROM AppBundle:IssledovanieFkuz if
                WHERE if.fkuz = :id and if.date >= :dateOt and if.date <= :dateDo 
                GROUP BY if.id
            ')
            ->setParameter('id', $id)
            ->setParameter('dateOt', $dateOt)
            ->setParameter('dateDo', $dateDo)
            ->getResult();
    }

    public function isslShowPokazatels($issl_id)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT pi.id, pi.description, pi.pokazatel FROM AppBundle:PokazatelsIssledovaniyaFkuz pi
                JOIN pi.issledovanieFkuz if
                WHERE if.id = :issl_id        
            ')
            ->setParameter('issl_id', $issl_id)
            ->getResult();
    }
}
