<?php

namespace AppBundle\Repository;

/**
 * PokazatelsIssledovaniyaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokazatelsIssledovaniyaRepository extends \Doctrine\ORM\EntityRepository
{
    //для редактированиния показателя
    public function isslEditNarusheniya($issl_id)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT pi.id, pi.description, pn.pokazatel FROM AppBundle:ProverkaIssledovaniy pi
                JOIN pi.issledovanie i
                WHERE pi.issledovanie = :issl_id        
            ')
            ->setParameter('issl_id', $issl_id)
            ->getResult();
    }
}
