<?php

namespace AppBundle\Repository;

/**
 * ProverkaFkuzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProverkaFkuzRepository extends \Doctrine\ORM\EntityRepository
{
    //наказания в карточке фкуз/филиала
    public function nakazaniya($id, $date)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT f.name_full, pnf.id, pnf.nomer, pnf.fio, pnf.date, pnf.dolgnost, pnf.zvanie, pnf.type, pnf.podchinennost FROM AppBundle:ProverkaFkuz pf
                JOIN pf.proverkaNakazanieFkuz pnf
                JOIN pf.fkuz f
                WHERE f.id = :id and YEAR(pnf.date) = :date           
                ORDER BY pnf.podchinennost DESC 
            ')
            ->setParameter('id', $id)
            ->setParameter('date', $date)
            ->getResult();
    }


    //кол-во нарушений по виду наказания
    public function nakazanieVid($vid)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT f.name_full, count(pnf.vid) FROM AppBundle:ProverkaNakazanieFkuz pnf
                JOIN pnf.proverkaFkuz pf
                JOIN pf.fkuz f
                WHERE pnf.vid = :vid            
                GROUP BY f.id
            ')
            ->setParameter('vid', $vid)
            ->getResult();
    }

    //кол-во нарушений по типу наказания
    public function nakazanieType($type)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT f.name_full, count(pnf.type) FROM AppBundle:ProverkaNakazanieFkuz pnf
                JOIN pnf.proverkaFkuz pf
                JOIN pf.fkuz f
                WHERE pnf.type = :type
                GROUP BY f.id
            ')
            ->setParameter('type', $type)
            ->getResult();
    }

    //кол-во людей по нарушениям
    public function nakazaniePeople($podch)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT f.name_full, count(pnf.podchinennost) FROM AppBundle:ProverkaNakazanieFkuz pnf
                JOIN pnf.proverkaFkuz pf
                JOIN pf.fkuz f
                WHERE pnf.podchinennost = :podch            
                GROUP BY f.id
            ')
            ->setParameter('podch', $podch)
            ->getResult();
    }
}
