<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Osugdenyi extends \AppBundle\Entity\Osugdenyi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'gender', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'fio', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_birthday', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'place_job', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'place_study', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'place_progivaniya', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_viyavleniya', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_vzyatiya_na_uchet', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'mbt', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_gospit', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_perevoda', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_zakl_dezin', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_post_v_org', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_obr', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'viyavlen', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'recidiv', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'postupil_iz', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'address_common', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'address_propiska', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'is_kontakt', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'datesFLG', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'soput_patol', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'kontaktnyi', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'ochag', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'organization');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'gender', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'fio', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_birthday', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'place_job', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'place_study', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'place_progivaniya', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_viyavleniya', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_vzyatiya_na_uchet', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'mbt', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_gospit', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_perevoda', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_zakl_dezin', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_post_v_org', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'date_obr', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'viyavlen', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'recidiv', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'postupil_iz', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'address_common', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'address_propiska', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'is_kontakt', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'datesFLG', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'soput_patol', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'kontaktnyi', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'ochag', '' . "\0" . 'AppBundle\\Entity\\Osugdenyi' . "\0" . 'organization');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Osugdenyi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setFio($fio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFio', array($fio));

        return parent::setFio($fio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFio', array());

        return parent::getFio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateBirthday($dateBirthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateBirthday', array($dateBirthday));

        return parent::setDateBirthday($dateBirthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateBirthday', array());

        return parent::getDateBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlace($place)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlace', array($place));

        return parent::setPlace($place);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlace', array());

        return parent::getPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateViyavleniya($dateViyavleniya)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateViyavleniya', array($dateViyavleniya));

        return parent::setDateViyavleniya($dateViyavleniya);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateViyavleniya()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateViyavleniya', array());

        return parent::getDateViyavleniya();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\AppBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function addKontaktnyus(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKontaktnyus', array($kontaktnyi));

        return parent::addKontaktnyus($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function addKont(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKont', array($kontaktnyi));

        return parent::addKont($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeKontaktnyus(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeKontaktnyus', array($kontaktnyi));

        return parent::removeKontaktnyus($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontaktnyi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontaktnyi', array());

        return parent::getKontaktnyi();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceJob($placeJob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceJob', array($placeJob));

        return parent::setPlaceJob($placeJob);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceJob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceJob', array());

        return parent::getPlaceJob();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceStudy($placeStudy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceStudy', array($placeStudy));

        return parent::setPlaceStudy($placeStudy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceStudy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceStudy', array());

        return parent::getPlaceStudy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceProgivaniya($placeProgivaniya)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceProgivaniya', array($placeProgivaniya));

        return parent::setPlaceProgivaniya($placeProgivaniya);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceProgivaniya()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceProgivaniya', array());

        return parent::getPlaceProgivaniya();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateVzyatiyaNaUchet($dateVzyatiyaNaUchet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateVzyatiyaNaUchet', array($dateVzyatiyaNaUchet));

        return parent::setDateVzyatiyaNaUchet($dateVzyatiyaNaUchet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateVzyatiyaNaUchet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateVzyatiyaNaUchet', array());

        return parent::getDateVzyatiyaNaUchet();
    }

    /**
     * {@inheritDoc}
     */
    public function setMbt($mbt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMbt', array($mbt));

        return parent::setMbt($mbt);
    }

    /**
     * {@inheritDoc}
     */
    public function getMbt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMbt', array());

        return parent::getMbt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateGospit($dateGospit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateGospit', array($dateGospit));

        return parent::setDateGospit($dateGospit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateGospit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateGospit', array());

        return parent::getDateGospit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePerevoda($datePerevoda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePerevoda', array($datePerevoda));

        return parent::setDatePerevoda($datePerevoda);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePerevoda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePerevoda', array());

        return parent::getDatePerevoda();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateZaklDezin($dateZaklDezin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateZaklDezin', array($dateZaklDezin));

        return parent::setDateZaklDezin($dateZaklDezin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateZaklDezin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateZaklDezin', array());

        return parent::getDateZaklDezin();
    }

    /**
     * {@inheritDoc}
     */
    public function addKontaktnyi(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKontaktnyi', array($kontaktnyi));

        return parent::addKontaktnyi($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeKontaktnyi(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeKontaktnyi', array($kontaktnyi));

        return parent::removeKontaktnyi($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsKontakt($isKontakt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsKontakt', array($isKontakt));

        return parent::setIsKontakt($isKontakt);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsKontakt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsKontakt', array());

        return parent::getIsKontakt();
    }

    /**
     * {@inheritDoc}
     */
    public function addOchag(\AppBundle\Entity\Ochag $ochag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOchag', array($ochag));

        return parent::addOchag($ochag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOchag(\AppBundle\Entity\Ochag $ochag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOchag', array($ochag));

        return parent::removeOchag($ochag);
    }

    /**
     * {@inheritDoc}
     */
    public function getOchag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOchag', array());

        return parent::getOchag();
    }

    /**
     * {@inheritDoc}
     */
    public function addOch(\AppBundle\Entity\Ochag $ochag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOch', array($ochag));

        return parent::addOch($ochag);
    }

    /**
     * {@inheritDoc}
     */
    public function setOchag(\AppBundle\Entity\Ochag $ochag = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOchag', array($ochag));

        return parent::setOchag($ochag);
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePostVOrg($datePostVOrg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePostVOrg', array($datePostVOrg));

        return parent::setDatePostVOrg($datePostVOrg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePostVOrg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePostVOrg', array());

        return parent::getDatePostVOrg();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateObr($dateObr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateObr', array($dateObr));

        return parent::setDateObr($dateObr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateObr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateObr', array());

        return parent::getDateObr();
    }

    /**
     * {@inheritDoc}
     */
    public function setViyavlen($viyavlen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViyavlen', array($viyavlen));

        return parent::setViyavlen($viyavlen);
    }

    /**
     * {@inheritDoc}
     */
    public function getViyavlen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViyavlen', array());

        return parent::getViyavlen();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecidiv($recidiv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecidiv', array($recidiv));

        return parent::setRecidiv($recidiv);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecidiv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecidiv', array());

        return parent::getRecidiv();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostupilIz($postupilIz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostupilIz', array($postupilIz));

        return parent::setPostupilIz($postupilIz);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostupilIz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostupilIz', array());

        return parent::getPostupilIz();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressCommon($addressCommon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressCommon', array($addressCommon));

        return parent::setAddressCommon($addressCommon);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressCommon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressCommon', array());

        return parent::getAddressCommon();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressPropiska($addressPropiska)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressPropiska', array($addressPropiska));

        return parent::setAddressPropiska($addressPropiska);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressPropiska()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressPropiska', array());

        return parent::getAddressPropiska();
    }

    /**
     * {@inheritDoc}
     */
    public function addDatesFLG(\AppBundle\Entity\DatesFLG $datesFLG)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDatesFLG', array($datesFLG));

        return parent::addDatesFLG($datesFLG);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDatesFLG(\AppBundle\Entity\DatesFLG $datesFLG)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDatesFLG', array($datesFLG));

        return parent::removeDatesFLG($datesFLG);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatesFLG()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatesFLG', array());

        return parent::getDatesFLG();
    }

    /**
     * {@inheritDoc}
     */
    public function addSoputPatol(\AppBundle\Entity\SoputPatol $soputPatol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSoputPatol', array($soputPatol));

        return parent::addSoputPatol($soputPatol);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSoputPatol(\AppBundle\Entity\SoputPatol $soputPatol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSoputPatol', array($soputPatol));

        return parent::removeSoputPatol($soputPatol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoputPatol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoputPatol', array());

        return parent::getSoputPatol();
    }

}
