<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ochag extends \AppBundle\Entity\Ochag implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'place', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'osugdenyi', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'kontaktnyi', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'organization');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'place', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'osugdenyi', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'kontaktnyi', '' . "\0" . 'AppBundle\\Entity\\Ochag' . "\0" . 'organization');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ochag $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function addOsugdenyus(\AppBundle\Entity\Osugdenyi $osugdenyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOsugdenyus', array($osugdenyi));

        return parent::addOsugdenyus($osugdenyi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOsugdenyus(\AppBundle\Entity\Osugdenyi $osugdenyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOsugdenyus', array($osugdenyi));

        return parent::removeOsugdenyus($osugdenyi);
    }

    /**
     * {@inheritDoc}
     */
    public function getOsugdenyi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOsugdenyi', array());

        return parent::getOsugdenyi();
    }

    /**
     * {@inheritDoc}
     */
    public function addKontaktnyus(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKontaktnyus', array($kontaktnyi));

        return parent::addKontaktnyus($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeKontaktnyus(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeKontaktnyus', array($kontaktnyi));

        return parent::removeKontaktnyus($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontaktnyi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontaktnyi', array());

        return parent::getKontaktnyi();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\AppBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function addOsugdenyi(\AppBundle\Entity\Osugdenyi $osugdenyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOsugdenyi', array($osugdenyi));

        return parent::addOsugdenyi($osugdenyi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOsugdenyi(\AppBundle\Entity\Osugdenyi $osugdenyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOsugdenyi', array($osugdenyi));

        return parent::removeOsugdenyi($osugdenyi);
    }

    /**
     * {@inheritDoc}
     */
    public function addKontaktnyi(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKontaktnyi', array($kontaktnyi));

        return parent::addKontaktnyi($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeKontaktnyi(\AppBundle\Entity\Kontaktnyi $kontaktnyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeKontaktnyi', array($kontaktnyi));

        return parent::removeKontaktnyi($kontaktnyi);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlace($place)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlace', array($place));

        return parent::setPlace($place);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlace', array());

        return parent::getPlace();
    }

}
