<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Objects extends \AppBundle\Entity\Objects implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'organization_id', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'dogovor_id', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'proverkanarushenie');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'organization_id', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'dogovor_id', '' . "\0" . 'AppBundle\\Entity\\Objects' . "\0" . 'proverkanarushenie');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Objects $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrganization(\AppBundle\Entity\Organization $organization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrganization', array($organization));

        return parent::addOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrganization(\AppBundle\Entity\Organization $organization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrganization', array($organization));

        return parent::removeOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogovor(\AppBundle\Entity\Dogovor $dogovor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogovor', array($dogovor));

        return parent::addDogovor($dogovor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogovor(\AppBundle\Entity\Dogovor $dogovor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogovor', array($dogovor));

        return parent::removeDogovor($dogovor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovor', array());

        return parent::getDogovor();
    }

    /**
     * {@inheritDoc}
     */
    public function addProverkaNarushenie(\AppBundle\Entity\ProverkaNarushenie $proverkaNarushenie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProverkaNarushenie', array($proverkaNarushenie));

        return parent::addProverkaNarushenie($proverkaNarushenie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProverkaNarushenie(\AppBundle\Entity\ProverkaNarushenie $proverkaNarushenie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProverkaNarushenie', array($proverkaNarushenie));

        return parent::removeProverkaNarushenie($proverkaNarushenie);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverkaNarushenie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverkaNarushenie', array());

        return parent::getProverkaNarushenie();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrganizationId(\AppBundle\Entity\Organization $organizationId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrganizationId', array($organizationId));

        return parent::addOrganizationId($organizationId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrganizationId(\AppBundle\Entity\Organization $organizationId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrganizationId', array($organizationId));

        return parent::removeOrganizationId($organizationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', array());

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogovorId(\AppBundle\Entity\Dogovor $dogovorId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogovorId', array($dogovorId));

        return parent::addDogovorId($dogovorId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogovorId(\AppBundle\Entity\Dogovor $dogovorId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogovorId', array($dogovorId));

        return parent::removeDogovorId($dogovorId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovorId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovorId', array());

        return parent::getDogovorId();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogovorObject(\AppBundle\Entity\Dogovor $dogovorObject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogovorObject', array($dogovorObject));

        return parent::addDogovorObject($dogovorObject);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogovorObject(\AppBundle\Entity\Dogovor $dogovorObject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogovorObject', array($dogovorObject));

        return parent::removeDogovorObject($dogovorObject);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovorObjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovorObjects', array());

        return parent::getDogovorObjects();
    }

}
