<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProverkaNakazanie extends \AppBundle\Entity\ProverkaNakazanie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'proverka', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'nomer', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'fio', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'dolgnost', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'zvanie', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'vid', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'podchinennost');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'proverka', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'nomer', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'fio', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'dolgnost', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'zvanie', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'vid', '' . "\0" . 'AppBundle\\Entity\\ProverkaNakazanie' . "\0" . 'podchinennost');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProverkaNakazanie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFio($fio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFio', array($fio));

        return parent::setFio($fio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFio', array());

        return parent::getFio();
    }

    /**
     * {@inheritDoc}
     */
    public function setProverka(\AppBundle\Entity\Proverka $proverka)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProverka', array($proverka));

        return parent::setProverka($proverka);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverka()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverka', array());

        return parent::getProverka();
    }

    /**
     * {@inheritDoc}
     */
    public function addNak(\AppBundle\Entity\Proverka $proverka)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNak', array($proverka));

        return parent::addNak($proverka);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomer($nomer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomer', array($nomer));

        return parent::setNomer($nomer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomer', array());

        return parent::getNomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDolgnost($dolgnost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDolgnost', array($dolgnost));

        return parent::setDolgnost($dolgnost);
    }

    /**
     * {@inheritDoc}
     */
    public function getDolgnost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDolgnost', array());

        return parent::getDolgnost();
    }

    /**
     * {@inheritDoc}
     */
    public function setZvanie($zvanie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZvanie', array($zvanie));

        return parent::setZvanie($zvanie);
    }

    /**
     * {@inheritDoc}
     */
    public function getZvanie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZvanie', array());

        return parent::getZvanie();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setVid($vid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVid', array($vid));

        return parent::setVid($vid);
    }

    /**
     * {@inheritDoc}
     */
    public function getVid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVid', array());

        return parent::getVid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPodchinennost($podchinennost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPodchinennost', array($podchinennost));

        return parent::setPodchinennost($podchinennost);
    }

    /**
     * {@inheritDoc}
     */
    public function getPodchinennost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPodchinennost', array());

        return parent::getPodchinennost();
    }

}
