<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Organization extends \AppBundle\Entity\Organization implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'name_full', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'name_short', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'ur_address', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'position', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'organizationMCH', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'rukovoditel', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'lichnyisostav', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'osugdenyi', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'ochag', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'issledovanie', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'proverka', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'dogovor', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'objects');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'name_full', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'name_short', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'ur_address', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'position', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'organizationMCH', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'rukovoditel', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'lichnyisostav', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'osugdenyi', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'ochag', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'issledovanie', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'proverka', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'dogovor', '' . "\0" . 'AppBundle\\Entity\\Organization' . "\0" . 'objects');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Organization $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrAddress($urAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrAddress', array($urAddress));

        return parent::setUrAddress($urAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrAddress', array());

        return parent::getUrAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizationMCHId($organizationMCHId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizationMCHId', array($organizationMCHId));

        return parent::setOrganizationMCHId($organizationMCHId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationMCHId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationMCHId', array());

        return parent::getOrganizationMCHId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRukovoditelId($rukovoditelId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRukovoditelId', array($rukovoditelId));

        return parent::setRukovoditelId($rukovoditelId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRukovoditelId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRukovoditelId', array());

        return parent::getRukovoditelId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizationMCH(\AppBundle\Entity\OrganizationMCH $organizationMCH = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizationMCH', array($organizationMCH));

        return parent::setOrganizationMCH($organizationMCH);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationMCH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationMCH', array());

        return parent::getOrganizationMCH();
    }

    /**
     * {@inheritDoc}
     */
    public function setRukovoditel(\AppBundle\Entity\Rukovoditel $rukovoditel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRukovoditel', array($rukovoditel));

        return parent::setRukovoditel($rukovoditel);
    }

    /**
     * {@inheritDoc}
     */
    public function getRukovoditel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRukovoditel', array());

        return parent::getRukovoditel();
    }

    /**
     * {@inheritDoc}
     */
    public function setProverka(\AppBundle\Entity\Proverka $proverka = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProverka', array($proverka));

        return parent::setProverka($proverka);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverka()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverka', array());

        return parent::getProverka();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogovor(\AppBundle\Entity\Dogovor $dogovor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogovor', array($dogovor));

        return parent::addDogovor($dogovor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogovor(\AppBundle\Entity\Dogovor $dogovor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogovor', array($dogovor));

        return parent::removeDogovor($dogovor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovor', array());

        return parent::getDogovor();
    }

    /**
     * {@inheritDoc}
     */
    public function addObject(\AppBundle\Entity\Objects $object)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObject', array($object));

        return parent::addObject($object);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObject(\AppBundle\Entity\Objects $object)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObject', array($object));

        return parent::removeObject($object);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjects', array());

        return parent::getObjects();
    }

    /**
     * {@inheritDoc}
     */
    public function addProverka(\AppBundle\Entity\Proverka $proverka)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProverka', array($proverka));

        return parent::addProverka($proverka);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProverka(\AppBundle\Entity\Proverka $proverka)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProverka', array($proverka));

        return parent::removeProverka($proverka);
    }

    /**
     * {@inheritDoc}
     */
    public function setLichnyisostav(\AppBundle\Entity\LichnyiSostav $lichnyisostav = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLichnyisostav', array($lichnyisostav));

        return parent::setLichnyisostav($lichnyisostav);
    }

    /**
     * {@inheritDoc}
     */
    public function getLichnyisostav()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLichnyisostav', array());

        return parent::getLichnyisostav();
    }

    /**
     * {@inheritDoc}
     */
    public function setOsugdenyi(\AppBundle\Entity\Osugdenyi $osugdenyi = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOsugdenyi', array($osugdenyi));

        return parent::setOsugdenyi($osugdenyi);
    }

    /**
     * {@inheritDoc}
     */
    public function getOsugdenyi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOsugdenyi', array());

        return parent::getOsugdenyi();
    }

    /**
     * {@inheritDoc}
     */
    public function addLichnyisostav(\AppBundle\Entity\LichnyiSostav $lichnyisostav)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLichnyisostav', array($lichnyisostav));

        return parent::addLichnyisostav($lichnyisostav);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLichnyisostav(\AppBundle\Entity\LichnyiSostav $lichnyisostav)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLichnyisostav', array($lichnyisostav));

        return parent::removeLichnyisostav($lichnyisostav);
    }

    /**
     * {@inheritDoc}
     */
    public function addOsugdenyi(\AppBundle\Entity\Osugdenyi $osugdenyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOsugdenyi', array($osugdenyi));

        return parent::addOsugdenyi($osugdenyi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOsugdenyi(\AppBundle\Entity\Osugdenyi $osugdenyi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOsugdenyi', array($osugdenyi));

        return parent::removeOsugdenyi($osugdenyi);
    }

    /**
     * {@inheritDoc}
     */
    public function setNameFull($nameFull)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameFull', array($nameFull));

        return parent::setNameFull($nameFull);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameFull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameFull', array());

        return parent::getNameFull();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameShort($nameShort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameShort', array($nameShort));

        return parent::setNameShort($nameShort);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameShort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameShort', array());

        return parent::getNameShort();
    }

    /**
     * {@inheritDoc}
     */
    public function addOchag(\AppBundle\Entity\Ochag $ochag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOchag', array($ochag));

        return parent::addOchag($ochag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOchag(\AppBundle\Entity\Ochag $ochag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOchag', array($ochag));

        return parent::removeOchag($ochag);
    }

    /**
     * {@inheritDoc}
     */
    public function getOchag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOchag', array());

        return parent::getOchag();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function addIssledovanie(\AppBundle\Entity\Issledovanie $issledovanie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIssledovanie', array($issledovanie));

        return parent::addIssledovanie($issledovanie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIssledovanie(\AppBundle\Entity\Issledovanie $issledovanie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIssledovanie', array($issledovanie));

        return parent::removeIssledovanie($issledovanie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssledovanie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssledovanie', array());

        return parent::getIssledovanie();
    }

}
