<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proverka extends \AppBundle\Entity\Proverka implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'nomer', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date_rasporyageniya', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date_akt', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date_predpisaniya', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'kem_vydano', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'organization', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'proverkaType', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'proverka_narushenie', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'proverka_nakazanie');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'nomer', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date_rasporyageniya', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date_akt', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'date_predpisaniya', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'kem_vydano', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'organization', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'proverkaType', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'proverka_narushenie', '' . "\0" . 'AppBundle\\Entity\\Proverka' . "\0" . 'proverka_nakazanie');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proverka $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomer($nomer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomer', array($nomer));

        return parent::setNomer($nomer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomer', array());

        return parent::getNomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRasporyageniya($dateRasporyageniya)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRasporyageniya', array($dateRasporyageniya));

        return parent::setDateRasporyageniya($dateRasporyageniya);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRasporyageniya()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRasporyageniya', array());

        return parent::getDateRasporyageniya();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAkt($dateAkt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAkt', array($dateAkt));

        return parent::setDateAkt($dateAkt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAkt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAkt', array());

        return parent::getDateAkt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePredpisaniya($datePredpisaniya)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePredpisaniya', array($datePredpisaniya));

        return parent::setDatePredpisaniya($datePredpisaniya);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePredpisaniya()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePredpisaniya', array());

        return parent::getDatePredpisaniya();
    }

    /**
     * {@inheritDoc}
     */
    public function setKemVydano($kemVydano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKemVydano', array($kemVydano));

        return parent::setKemVydano($kemVydano);
    }

    /**
     * {@inheritDoc}
     */
    public function getKemVydano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKemVydano', array());

        return parent::getKemVydano();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizationId($organizationId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizationId', array($organizationId));

        return parent::setOrganizationId($organizationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', array());

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProverkaTypeId($proverkaTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProverkaTypeId', array($proverkaTypeId));

        return parent::setProverkaTypeId($proverkaTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverkaTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverkaTypeId', array());

        return parent::getProverkaTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\AppBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setProverkaType(\AppBundle\Entity\ProverkaType $proverkaType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProverkaType', array($proverkaType));

        return parent::setProverkaType($proverkaType);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverkaType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverkaType', array());

        return parent::getProverkaType();
    }

    /**
     * {@inheritDoc}
     */
    public function addProverkaNarushenie(\AppBundle\Entity\ProverkaNarushenie $proverkaNarushenie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProverkaNarushenie', array($proverkaNarushenie));

        return parent::addProverkaNarushenie($proverkaNarushenie);
    }

    /**
     * {@inheritDoc}
     */
    public function addNarushenie(\AppBundle\Entity\ProverkaNarushenie $proverkaNarushenie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNarushenie', array($proverkaNarushenie));

        return parent::addNarushenie($proverkaNarushenie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProverkaNarushenie(\AppBundle\Entity\ProverkaNarushenie $proverkaNarushenie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProverkaNarushenie', array($proverkaNarushenie));

        return parent::removeProverkaNarushenie($proverkaNarushenie);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverkaNarushenie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverkaNarushenie', array());

        return parent::getProverkaNarushenie();
    }

    /**
     * {@inheritDoc}
     */
    public function addProverkaNakazanie(\AppBundle\Entity\ProverkaNakazanie $proverkaNakazanie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProverkaNakazanie', array($proverkaNakazanie));

        return parent::addProverkaNakazanie($proverkaNakazanie);
    }

    /**
     * {@inheritDoc}
     */
    public function addNakazanie(\AppBundle\Entity\ProverkaNakazanie $proverkaNakazanie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNakazanie', array($proverkaNakazanie));

        return parent::addNakazanie($proverkaNakazanie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProverkaNakazanie(\AppBundle\Entity\ProverkaNakazanie $proverkaNakazanie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProverkaNakazanie', array($proverkaNakazanie));

        return parent::removeProverkaNakazanie($proverkaNakazanie);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverkaNakazanie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverkaNakazanie', array());

        return parent::getProverkaNakazanie();
    }

}
