<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fkuz extends \AppBundle\Entity\Fkuz implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'name_full', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'name_short', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'rukovoditel', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'license', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'dogovorFkuz', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'proverkaFkuz', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'issledovanieFkuz');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'name_full', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'name_short', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'rukovoditel', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'license', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'dogovorFkuz', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'proverkaFkuz', '' . "\0" . 'AppBundle\\Entity\\Fkuz' . "\0" . 'issledovanieFkuz');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fkuz $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameFull($nameFull)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameFull', array($nameFull));

        return parent::setNameFull($nameFull);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameFull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameFull', array());

        return parent::getNameFull();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameShort($nameShort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameShort', array($nameShort));

        return parent::setNameShort($nameShort);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameShort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameShort', array());

        return parent::getNameShort();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setRukovoditel(\AppBundle\Entity\Rukovoditel $rukovoditel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRukovoditel', array($rukovoditel));

        return parent::setRukovoditel($rukovoditel);
    }

    /**
     * {@inheritDoc}
     */
    public function getRukovoditel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRukovoditel', array());

        return parent::getRukovoditel();
    }

    /**
     * {@inheritDoc}
     */
    public function addLicense(\AppBundle\Entity\License $license)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLicense', array($license));

        return parent::addLicense($license);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLicense(\AppBundle\Entity\License $license)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLicense', array($license));

        return parent::removeLicense($license);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicense', array());

        return parent::getLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogovorFkuz(\AppBundle\Entity\DogovorFkuz $dogovorFkuz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogovorFkuz', array($dogovorFkuz));

        return parent::addDogovorFkuz($dogovorFkuz);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogovorFkuz(\AppBundle\Entity\DogovorFkuz $dogovorFkuz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogovorFkuz', array($dogovorFkuz));

        return parent::removeDogovorFkuz($dogovorFkuz);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovorFkuz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovorFkuz', array());

        return parent::getDogovorFkuz();
    }

    /**
     * {@inheritDoc}
     */
    public function addProverkaFkuz(\AppBundle\Entity\Proverka $proverkaFkuz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProverkaFkuz', array($proverkaFkuz));

        return parent::addProverkaFkuz($proverkaFkuz);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProverkaFkuz(\AppBundle\Entity\Proverka $proverkaFkuz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProverkaFkuz', array($proverkaFkuz));

        return parent::removeProverkaFkuz($proverkaFkuz);
    }

    /**
     * {@inheritDoc}
     */
    public function getProverkaFkuz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProverkaFkuz', array());

        return parent::getProverkaFkuz();
    }

    /**
     * {@inheritDoc}
     */
    public function addIssledovanieFkuz(\AppBundle\Entity\IssledovanieFkuz $issledovanieFkuz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIssledovanieFkuz', array($issledovanieFkuz));

        return parent::addIssledovanieFkuz($issledovanieFkuz);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIssledovanieFkuz(\AppBundle\Entity\IssledovanieFkuz $issledovanieFkuz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIssledovanieFkuz', array($issledovanieFkuz));

        return parent::removeIssledovanieFkuz($issledovanieFkuz);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssledovanieFkuz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssledovanieFkuz', array());

        return parent::getIssledovanieFkuz();
    }

}
