<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dogovor extends \AppBundle\Entity\Dogovor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'nomer', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'organization_posrednik', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'summa', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'dogovor_objects', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'organization', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'dogovorType');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'nomer', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'organization_posrednik', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'summa', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'dogovor_objects', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'organization', '' . "\0" . 'AppBundle\\Entity\\Dogovor' . "\0" . 'dogovorType');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dogovor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomer($nomer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomer', array($nomer));

        return parent::setNomer($nomer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomer', array());

        return parent::getNomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizationPosrednik($organizationPosrednik)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizationPosrednik', array($organizationPosrednik));

        return parent::setOrganizationPosrednik($organizationPosrednik);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationPosrednik()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationPosrednik', array());

        return parent::getOrganizationPosrednik();
    }

    /**
     * {@inheritDoc}
     */
    public function setSumma($summa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSumma', array($summa));

        return parent::setSumma($summa);
    }

    /**
     * {@inheritDoc}
     */
    public function getSumma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSumma', array());

        return parent::getSumma();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogovorObject(\AppBundle\Entity\Objects $dogovorObject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogovorObject', array($dogovorObject));

        return parent::addDogovorObject($dogovorObject);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogovorObject(\AppBundle\Entity\Objects $dogovorObject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogovorObject', array($dogovorObject));

        return parent::removeDogovorObject($dogovorObject);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovorObjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovorObjects', array());

        return parent::getDogovorObjects();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\AppBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogovorTypeId(\AppBundle\Entity\DogovorType $dogovorTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogovorTypeId', array($dogovorTypeId));

        return parent::addDogovorTypeId($dogovorTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogovorTypeId(\AppBundle\Entity\DogovorType $dogovorTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogovorTypeId', array($dogovorTypeId));

        return parent::removeDogovorTypeId($dogovorTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovorTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovorTypeId', array());

        return parent::getDogovorTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDogovorTypeId(\AppBundle\Entity\DogovorType $dogovorTypeId = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDogovorTypeId', array($dogovorTypeId));

        return parent::setDogovorTypeId($dogovorTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function setDogovorType(\AppBundle\Entity\DogovorType $dogovorType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDogovorType', array($dogovorType));

        return parent::setDogovorType($dogovorType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogovorType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogovorType', array());

        return parent::getDogovorType();
    }

    /**
     * {@inheritDoc}
     */
    public function addObject(\AppBundle\Entity\Objects $object)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObject', array($object));

        return parent::addObject($object);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObject(\AppBundle\Entity\Objects $object)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObject', array($object));

        return parent::removeObject($object);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjects', array());

        return parent::getObjects();
    }

}
